
vllm:
  enabled: false
tgi:
  enabled: false

endpoint:
  enabled: true
  LLM_MODEL_ID: "standard-qwen-25-7b"

modelcar:
  endpoints:
    llm:
      host: "standard-qwen-25-7b-predictor.ed-modelcar.svc.cluster.local"
      port: "8080"