fullnameOverride: qwen-25-7b
displaynameOverride: Qwen 2.5 7B Instruct
model:
  uri: oci://quay.io/redhat-ai-services/modelcar-catalog:qwen2.5-7b-instruct
  extraArgs:
  - --max-model-len=16384
progressDeadline: 60m
 
# Use Gaudi
image:
  repository: modh/vllm
  manifestHash: af6a071be36d8a99476f145d1589d7ede97d2760b93335b14ca26de7417e438c
recommendedAccelerators: '["habana.ai/gaudi"]'
acceleratorName: gaudi-hpu-profile
rhoaiTemplate:
  name: vllm-gaudi-runtime
  displayName: vLLM Intel Gaudi Accelerator ServingRuntime for KServe
resources:
  limits:
    nvidia.com/gpu: null
    habana.ai/gaudi: 1
  requests:
    nvidia.com/gpu: null
    habana.ai/gaudi: 1
tolerations: null